# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'enhanceUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_EnhanceForm(object):
    def setupUi(self, EnhanceForm):
        EnhanceForm.setObjectName("EnhanceForm")
        EnhanceForm.resize(234, 292)
        self.label = QtWidgets.QLabel(EnhanceForm)
        self.label.setGeometry(QtCore.QRect(20, 30, 59, 16))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.brightnessSlide = QtWidgets.QSlider(EnhanceForm)
        self.brightnessSlide.setGeometry(QtCore.QRect(20, 51, 191, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.brightnessSlide.sizePolicy().hasHeightForWidth())
        self.brightnessSlide.setSizePolicy(sizePolicy)
        self.brightnessSlide.setMaximum(30)
        self.brightnessSlide.setSingleStep(10)
        self.brightnessSlide.setProperty("value", 10)
        self.brightnessSlide.setTracking(True)
        self.brightnessSlide.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlide.setInvertedAppearance(False)
        self.brightnessSlide.setInvertedControls(False)
        self.brightnessSlide.setObjectName("brightnessSlide")
        self.label_2 = QtWidgets.QLabel(EnhanceForm)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 60, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.sharpnessSlide = QtWidgets.QSlider(EnhanceForm)
        self.sharpnessSlide.setGeometry(QtCore.QRect(20, 111, 191, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sharpnessSlide.sizePolicy().hasHeightForWidth())
        self.sharpnessSlide.setSizePolicy(sizePolicy)
        self.sharpnessSlide.setMaximum(30)
        self.sharpnessSlide.setProperty("value", 10)
        self.sharpnessSlide.setOrientation(QtCore.Qt.Horizontal)
        self.sharpnessSlide.setObjectName("sharpnessSlide")
        self.colorSlide = QtWidgets.QSlider(EnhanceForm)
        self.colorSlide.setGeometry(QtCore.QRect(20, 181, 191, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.colorSlide.sizePolicy().hasHeightForWidth())
        self.colorSlide.setSizePolicy(sizePolicy)
        self.colorSlide.setMaximum(30)
        self.colorSlide.setSingleStep(10)
        self.colorSlide.setProperty("value", 10)
        self.colorSlide.setOrientation(QtCore.Qt.Horizontal)
        self.colorSlide.setObjectName("colorSlide")
        self.label_3 = QtWidgets.QLabel(EnhanceForm)
        self.label_3.setGeometry(QtCore.QRect(20, 160, 30, 16))
        self.label_3.setObjectName("label_3")
        self.contrastSlide = QtWidgets.QSlider(EnhanceForm)
        self.contrastSlide.setGeometry(QtCore.QRect(20, 261, 191, 17))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contrastSlide.sizePolicy().hasHeightForWidth())
        self.contrastSlide.setSizePolicy(sizePolicy)
        self.contrastSlide.setMaximum(30)
        self.contrastSlide.setSliderPosition(10)
        self.contrastSlide.setOrientation(QtCore.Qt.Horizontal)
        self.contrastSlide.setObjectName("contrastSlide")
        self.label_4 = QtWidgets.QLabel(EnhanceForm)
        self.label_4.setGeometry(QtCore.QRect(20, 240, 48, 16))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(EnhanceForm)
        QtCore.QMetaObject.connectSlotsByName(EnhanceForm)

    def retranslateUi(self, EnhanceForm):
        _translate = QtCore.QCoreApplication.translate
        EnhanceForm.setWindowTitle(_translate("EnhanceForm", "Form"))
        self.label.setText(_translate("EnhanceForm", "Brightness"))
        self.label_2.setText(_translate("EnhanceForm", "Sharpness"))
        self.label_3.setText(_translate("EnhanceForm", "Color"))
        self.label_4.setText(_translate("EnhanceForm", "Contrast"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    EnhanceForm = QtWidgets.QWidget()
    ui = Ui_EnhanceForm()
    ui.setupUi(EnhanceForm)
    EnhanceForm.show()
    sys.exit(app.exec_())
