# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FilterUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilterDialog(object):
    def setupUi(self, FilterDialog):
        FilterDialog.setObjectName("FilterDialog")
        FilterDialog.resize(321, 170)
        self.pushButton = QtWidgets.QPushButton(FilterDialog)
        self.pushButton.setGeometry(QtCore.QRect(9, 9, 131, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(FilterDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 60, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_4 = QtWidgets.QPushButton(FilterDialog)
        self.pushButton_4.setGeometry(QtCore.QRect(160, 110, 141, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(FilterDialog)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 110, 131, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_7 = QtWidgets.QPushButton(FilterDialog)
        self.pushButton_7.setGeometry(QtCore.QRect(160, 10, 141, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(FilterDialog)
        self.pushButton_8.setGeometry(QtCore.QRect(160, 60, 141, 41))
        self.pushButton_8.setObjectName("pushButton_8")

        self.retranslateUi(FilterDialog)
        QtCore.QMetaObject.connectSlotsByName(FilterDialog)

    def retranslateUi(self, FilterDialog):
        _translate = QtCore.QCoreApplication.translate
        FilterDialog.setWindowTitle(_translate("FilterDialog", "Filter Dialog"))
        self.pushButton.setText(_translate("FilterDialog", "Blur"))
        self.pushButton_2.setText(_translate("FilterDialog", "Contour"))
        self.pushButton_4.setText(_translate("FilterDialog", "Edge Enhance"))
        self.pushButton_5.setText(_translate("FilterDialog", "Detail"))
        self.pushButton_7.setText(_translate("FilterDialog", "Sharpen"))
        self.pushButton_8.setText(_translate("FilterDialog", "Smooth"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FilterDialog = QtWidgets.QDialog()
    ui = Ui_FilterDialog()
    ui.setupUi(FilterDialog)
    FilterDialog.show()
    sys.exit(app.exec_())
