# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HistoryUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistoryDialog(object):
    def setupUi(self, HistoryDialog):
        HistoryDialog.setObjectName("HistoryDialog")
        HistoryDialog.resize(422, 300)
        self.scrollArea = QtWidgets.QScrollArea(HistoryDialog)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 431, 251))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 429, 249))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(0, 0, 421, 251))
        self.listWidget.setIconSize(QtCore.QSize(250, 120))
        self.listWidget.setObjectName("listWidget")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton = QtWidgets.QPushButton(HistoryDialog)
        self.pushButton.setGeometry(QtCore.QRect(320, 260, 93, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(HistoryDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 260, 91, 31))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(HistoryDialog)
        QtCore.QMetaObject.connectSlotsByName(HistoryDialog)

    def retranslateUi(self, HistoryDialog):
        _translate = QtCore.QCoreApplication.translate
        HistoryDialog.setWindowTitle(_translate("HistoryDialog", "History"))
        self.pushButton.setText(_translate("HistoryDialog", "Delete"))
        self.pushButton_2.setText(_translate("HistoryDialog", "Apply"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HistoryDialog = QtWidgets.QDialog()
    ui = Ui_HistoryDialog()
    ui.setupUi(HistoryDialog)
    HistoryDialog.show()
    sys.exit(app.exec_())
