# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResizeUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResizeDialog(object):
    def setupUi(self, ResizeDialog):
        ResizeDialog.setObjectName("ResizeDialog")
        ResizeDialog.resize(325, 222)
        self.label = QtWidgets.QLabel(ResizeDialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(ResizeDialog)
        self.label_2.setGeometry(QtCore.QRect(30, 90, 111, 41))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.sbWidth = QtWidgets.QSpinBox(ResizeDialog)
        self.sbWidth.setGeometry(QtCore.QRect(160, 20, 141, 41))
        self.sbWidth.setMaximum(100000)
        self.sbWidth.setObjectName("sbWidth")
        self.sbHeight = QtWidgets.QSpinBox(ResizeDialog)
        self.sbHeight.setGeometry(QtCore.QRect(160, 90, 141, 41))
        self.sbHeight.setMaximum(100000)
        self.sbHeight.setObjectName("sbHeight")
        self.pushButton = QtWidgets.QPushButton(ResizeDialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 150, 121, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(ResizeDialog)
        self.pushButton_2.setGeometry(QtCore.QRect(170, 150, 131, 41))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(ResizeDialog)
        QtCore.QMetaObject.connectSlotsByName(ResizeDialog)

    def retranslateUi(self, ResizeDialog):
        _translate = QtCore.QCoreApplication.translate
        ResizeDialog.setWindowTitle(_translate("ResizeDialog", "Resize"))
        self.label.setText(_translate("ResizeDialog", "Width(px):"))
        self.label_2.setText(_translate("ResizeDialog", "Height(px):"))
        self.pushButton.setText(_translate("ResizeDialog", "Apply"))
        self.pushButton_2.setText(_translate("ResizeDialog", "Undo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ResizeDialog = QtWidgets.QDialog()
    ui = Ui_ResizeDialog()
    ui.setupUi(ResizeDialog)
    ResizeDialog.show()
    sys.exit(app.exec_())
